# -*- coding: utf-8 -*-
#Lab 5. Peng-Robinson.ipynb

#Automatically generated by Colaboratory.

#Original file is located at
#    https://colab.research.google.com/drive/1NJy0Kah6lAUbd9sxgIJ2Fz61VvGe_S-E
#

#!pip install thermo

from thermo import ChemicalConstantsPackage, CEOSGas, CEOSLiquid, PRMIX, FlashVL, FlashVLN, FlashPureVLS
from thermo.interaction_parameters import IPDB
# Load constants and properties
constants, properties = ChemicalConstantsPackage.from_IDs(['acetone', 'water'])
# Objects are initialized at a particular condition
T = 333.15 # K
P = 1e5 # 1 bar
zs = [.5, .5]

# Use Peng-Robinson for both the vapor and the liquid phases
k12 = -0.2477
kijs = [[0, k12],
        [k12, 0]]
print(k12)
eos_kwargs = dict(Tcs=constants.Tcs, Pcs=constants.Pcs, omegas=constants.omegas, kijs=kijs)
gas = CEOSGas(PRMIX, eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases, T=T, P=P, zs=zs)
liquid = CEOSLiquid(PRMIX, eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases, T=T, P=P, zs=zs)
#gas = CEOSGas(PRMIX, eos_kwargs=eos_kwargs)
#liquid = CEOSLiquid(PRMIX, eos_kwargs=eos_kwargs)

# Create a flasher instance, assuming only vapor-liquid behavior
flasher = FlashVL(constants, properties, liquid=liquid, gas=gas)

# Create a T-xy plot at P bar
_ = flasher.plot_Txy(P=P, pts=100)

# Create a P-xy plot at T Kelvin
_ = flasher.plot_Pxy(T=T, pts=100)

# Create a xy diagram at T Kelvin
_ = flasher.plot_xy(T=T, pts=100)

# VLLE flash
liquid2 = CEOSLiquid(PRMIX, eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases, T=T, P=P, zs=zs)
flasher2 = FlashVLN(constants, properties, liquids=[liquid, liquid2], gas=gas)

x1_exp=[0.01, 0.03, 0.1, 0.5, 0.85];
y1_exp=[0.250369, 0.494505, 0.725424, 0.839958, 0.908808];

myT=[365.699, 355.741, 342.005, 332.748, 330.14];

#initial mole fractions of component 1 to start flash from
#take this between x and y at plot. At first glance, between x1_exp and y1_exp
zs=[0.1, 0.2, 0.7, 0.9, 0.97]

for i in range(5):
	res = flasher2.flash(T=myT[i], P=P, zs=[zs[i], 1-zs[i]])
	print('There are %s phases present at %f K and %f bar' %(res.phase_count,myT[i],P/1e5))
	if res.VF == 0:
		print("Only liquid")
	if res.VF > 0:
		print("x: ")
		print(res.gas.zs)
	if res.VF == 1:  # Есть только пар
		print("Only vapour")
	else:
		print("Liquid0: ")
		print(res.liquid0.zs)
		if res.liquid_count>1:
			print("LIQUID PHASE SEPARATION")
			print("Liquid1: ")
			print(res.liquid1.zs)

